spring:
  profiles:
    active: test #默认运行环境
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.35:8848  #Nacos 链接地址
        namespace: db7e9f2d-4b3c-4f8b-b1b1-696a1862112f #Nacos 命名空间ID

dubbo:
  cloud:
    subscribed-services: dynamic-datasource-core
  consumer:
    timeout: 3000
# 服务端口
server:
  port: 8125