spring:
  profiles:
    active: test #默认运行环境
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.35:8848  #Nacos 链接地址
        namespace: db7e9f2d-4b3c-4f8b-b1b1-696a1862112f #Nacos 命名空间ID

dubbo:
  cloud:
    subscribed-services: dynamic-datasource-core
  consumer:
    timeout: 3000
  registry:
    address: nacos://172.16.0.35:8848
  protocol:
    port: 20882
    host: 192.168.200.150
# 服务端口
server:
  port: 8125


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: nacos_consumer_tx_group
  grouplist: 172.16.0.20:8091
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.16.0.35:8848
      group: SEATA_20
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 172.16.0.35:8848
      group: SEATA_20
      username: nacos
      password: nacos
      cluster: default
  service:
    vgroup-mapping:
      nacos_consumer_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
    tm:
      rollbackRetryCount: '3'
      commitRetryCount: '3'
