spring:
  profiles:
    active: test #默认运行环境
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.35:8848  #Nacos 链接地址
        namespace: db7e9f2d-4b3c-4f8b-b1b1-696a1862112f #Nacos 命名空间ID
#dynamic-datasource:
#  default:
#    tenantId: 3
dubbo:
  cloud:
    subscribed-services: dynamic-datasource-core
  consumer:
    timeout: 3000
  spring:
    application:
      # Dubbo 应用名称
      name: dubbo-consumer
    main:
      # Spring Boot 2.1 需要设定
      allow-bean-definition-overriding: true
  registry:
    address: nacos://172.16.0.35:8848
  protocol:
    port: 20882
# 服务端口
server:
  port: 8125

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false # 禁止大写变小写时自动添加下划线
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 默认动态数据源配置
dynamic-datasource:
  default:
    url: jdbc:mysql://172.16.0.20:3306/lamp?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: mysqlpasswd
    driverClassName: com.mysql.cj.jdbc.Driver